---
- hosts: webservers
  become: true

  vars:
  - imageName

  tasks:
  - name: stop current running container
    command: docker stop myapp
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm myapp
    ignore_errors: yes

  - name: remove docker image
    command: docker image rm morrisyuen/test
    ignore_errors: yes

  - name: create container using morrisyuen/test
    command: docker run -d --name myapp -p 8080:80 {{imageName}}

