---
- hosts: localhosts
  become: true

  tasks:
  - name: build docker iamge
    command: sudo docker build -t nginxtest .
    args:
      chdir: /var/lib/jenkins/workspace/Deploy_to_DockerHost_with_Ansible
